---
- name: Assert that prerequisites exist
  tags: newrelic-sysmond
  assert:
    that:
      - newrelic_sysmond_license_key is defined

- name: Ensure that newrelic-sysmond is installed
  tags: newrelic-sysmond
  yum:
    enablerepo: newrelic
    name: newrelic-sysmond
    state: present
    update_cache: yes
  register: newrelic_sysmond_yum

- block:
  - name: Apply newrelic-sysmond configuration
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dst }}"
      owner: root
      group: "{{ item.group }}"
      mode: "{{ item.mode }}"
    notify: restart newrelic-sysmond
    with_items:
      - { src: nrsysmond.cfg.j2, dst: /etc/newrelic/nrsysmond.cfg, group: newrelic, mode: '0640' }
      - { src: newrelic-sysmond.sysconfig.j2, dst: /etc/sysconfig/newrelic-sysmond, group: root, mode: '0644' }

  - name: Start the newrelic-sysmond service and enable on boot
    service:
      enabled: yes
      name: newrelic-sysmond
      state: started
  tags: newrelic-sysmond
  when: newrelic_sysmond_yum|success
...
