---
- name: Ensure that the newrelic-sysmond package is installed
  tags: newrelic_sysmond
  become: true
  yum:
    enablerepo: newrelic
    name: newrelic-sysmond
    state: present
  register: newrelic_sysmond_yum

- block:
  - name: Applying newrelic-sysmond configurations
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dst }}"
      owner: root
      group: "{{ item.group }}"
      mode: "{{ item.mode }}"
    notify: restart newrelic-sysmond
    with_items:
      - { src: nrsysmond.cfg.j2, dst: /etc/newrelic/nrsysmond.cfg, group: newrelic, mode: '0640' }
      - { src: newrelic-sysmond.sysconfig.j2, dst: /etc/sysconfig/newrelic-sysmond, group: root, mode: '0644' }

  - name: Enable and start the newrelic-sysmond service on boot
    service:
      enabled: yes
      name: newrelic-sysmond
      state: started
  tags: newrelic_sysmond
  become: true
  when: newrelic_sysmond_yum|success
...
